default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  database: cfc_backend_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: cfc_backend_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: cfc_backend_production
  pool: 5
  timeout: 5000
